update race_weekend set country = 'Azerbaijan' where country = 'azerbaijan';
update race_weekend set country = 'United Arab Emirates' where country = 'Abu_Dhabi';
update race_weekend set country = 'United Arab Emirates' where country = 'abu-dhabi';
update race_weekend set country = 'Australia' where country = 'australia';
update race_weekend set country = 'Austria' where country = 'austria';
update race_weekend set country = 'Bahrain' where country ='bahrain';
update race_weekend set country = 'Belgium' where country ='belgium';
update race_weekend set country = 'Brazil' where country ='brasil';
update race_weekend set country = 'Canada' where country ='canada';
update race_weekend set country = 'China' where country ='china';
update race_weekend set country = 'United Kingdom' where country ='great-britain';
update race_weekend set country = 'United Kingdom' where country ='United_Kingdom';
update race_weekend set country = 'Hungary' where country ='hungary';
update race_weekend set country = 'Italy' where country ='italy';
update race_weekend set country = 'Japan' where country ='japan';
update race_weekend set country = 'Mexico' where country ='mexico';
update race_weekend set country = 'Monaco' where country ='monaco';
update race_weekend set country = 'Netherlands' where country ='netherlands';
update race_weekend set country = 'Qatar' where country ='qatar';
update race_weekend set country = 'Saudi Arabia' where country ='saudi-arabia';
update race_weekend set country = 'Singapore' where country ='singapore';
update race_weekend set country = 'Spain' where country ='spain';
update race_weekend set country = 'United States' where country ='usa';
update race_weekend set country = 'United States' where country ='USA';
