delete from fan;

INSERT INTO public.fan (id, name) VALUES (2, 'Ewa');
INSERT INTO public.fan (id, name) VALUES (3, 'Jeppe');
INSERT INTO public.fan (id, name) VALUES (1, 'Perty');

delete from race_weekend;

INSERT INTO public.race_weekend (id, name, weekend_type) VALUES (1, 'Bahrains GP', 'CLASSIC');
INSERT INTO public.race_weekend (id, name, weekend_type) VALUES (2, 'Saudi-Arabiens GP', 'CLASSIC');
INSERT INTO public.race_weekend (id, name, weekend_type) VALUES (3, 'Australiens GP', 'CLASSIC');
INSERT INTO public.race_weekend (id, name, weekend_type) VALUES (4, 'Japans GP', 'CLASSIC');
INSERT INTO public.race_weekend (id, name, weekend_type) VALUES (5, 'Kinas GP', 'SPRINT');
INSERT INTO public.race_weekend (id, name, weekend_type) VALUES (6, 'Miamis GP', 'SPRINT');
INSERT INTO public.race_weekend (id, name, weekend_type) VALUES (7, 'Emilia Romagnas GP', 'CLASSIC');
INSERT INTO public.race_weekend (id, name, weekend_type) VALUES (8, 'Monacos GP', 'CLASSIC');
INSERT INTO public.race_weekend (id, name, weekend_type) VALUES (9, 'Kanadas GP', 'CLASSIC');
INSERT INTO public.race_weekend (id, name, weekend_type) VALUES (10, 'Spaniens GP', 'CLASSIC');
INSERT INTO public.race_weekend (id, name, weekend_type) VALUES (11, 'Österrikes GP', 'SPRINT');
INSERT INTO public.race_weekend (id, name, weekend_type) VALUES (12, 'Storbritanniens GP', 'CLASSIC');
INSERT INTO public.race_weekend (id, name, weekend_type) VALUES (13, 'Ungerns GP', 'CLASSIC');
INSERT INTO public.race_weekend (id, name, weekend_type) VALUES (14, 'Belgiens GP', 'CLASSIC');
INSERT INTO public.race_weekend (id, name, weekend_type) VALUES (15, 'Nederländernas GP', 'CLASSIC');
INSERT INTO public.race_weekend (id, name, weekend_type) VALUES (16, 'Italiens GP', 'CLASSIC');
INSERT INTO public.race_weekend (id, name, weekend_type) VALUES (17, 'Azerbajdzjans GP', 'CLASSIC');
INSERT INTO public.race_weekend (id, name, weekend_type) VALUES (18, 'Singapores GP', 'CLASSIC');
INSERT INTO public.race_weekend (id, name, weekend_type) VALUES (19, 'USAs GP', 'SPRINT');
INSERT INTO public.race_weekend (id, name, weekend_type) VALUES (20, 'Mexikos GP', 'CLASSIC');
INSERT INTO public.race_weekend (id, name, weekend_type) VALUES (21, 'Brasiliens GP', 'SPRINT');
INSERT INTO public.race_weekend (id, name, weekend_type) VALUES (22, 'Las Vegas GP', 'CLASSIC');
INSERT INTO public.race_weekend (id, name, weekend_type) VALUES (23, 'Qatars GP', 'SPRINT');
INSERT INTO public.race_weekend (id, name, weekend_type) VALUES (24, 'Abu Dhabis GP', 'CLASSIC');

delete from statement;

INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (1, 'En Ferrari tar pole', false, true, true, false);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (2, 'Sargeant kvalar sist', false, true, true, false);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (3, 'Medveten ”tow” till stallkompisen', false, true, true, false);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (4, 'Någon säger ”pip” under kvalet', false, true, true, false);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (5, 'Rödflagg under kvalet', false, true, true, false);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (6, 'Haas eller Williams går till Q3', false, true, true, false);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (7, 'En Red Bull åker ut i Q2', false, true, true, false);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (8, 'En Red Bull åker ut i Q1', false, true, true, false);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (9, 'En förare kvalar för första gången bland de 10 bästa', false, true, true, false);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (10, 'En av A-bilarna tar pole', false, true, true, false);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (11, 'En Mercedes tar pole', false, true, true, false);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (12, 'Verstappen tar pole', false, true, true, false);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (13, 'Perez tar pole', false, true, true, false);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (14, 'En Aston Martin tar pole', false, true, true, false);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (15, 'En förare missar chans till snabb tid pga trafik', false, true, true, false);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (16, 'Stroll blir en av de tre bästa i kvalet', false, true, true, false);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (17, 'En tredjeförare får köra kvalet', false, true, true, false);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (18, 'Det blir ett regnkval = Intermediates sitter på någon bil', false, true, true, false);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (19, 'En bil tappar en del', false, true, true, false);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (20, 'En av A-bilarna orsakar gulflagg under kvalet', false, true, true, false);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (21, 'En McLaren kommer sist i kvalet', false, true, true, false);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (22, 'En förare får straff innan kval', false, true, true, false);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (23, 'En McLaren går till Q3', false, true, true, false);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (24, 'En Aston Martin åker ut i Q1', false, true, true, false);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (25, 'En Aston Martin åker ut i Q2', false, true, true, false);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (26, 'En Ferrari åker ut i Q1', false, true, true, false);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (27, 'En Ferrari åker ut i Q2', false, true, true, false);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (28, 'En Mercedes åker ut i Q1', false, true, true, false);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (29, 'En Mercedes åker ut i Q2', false, true, true, false);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (30, 'En förare får sin tid struken pga track limits', false, true, true, false);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (31, 'En förare får straff för impeding under kvalet', false, true, true, false);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (32, 'En av Alpineförarna kvalar topp 3', false, true, true, false);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (33, 'Kvalstarten blir uppskjuten av någon anledning', false, true, true, false);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (34, 'En bil bryter under kvalet', false, true, true, false);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (35, 'Hulkenberg och Magnusen råkar i luven på varandra', true, false, false, true);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (36, 'Gasly och Ocon kommer ihop sig under racet', true, false, false, true);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (37, 'En bil börjar brinna', true, false, false, true);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (38, 'Hamilton och Verstappen kraschar i varandra', true, false, false, true);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (39, 'Tsunoda kraschar', true, false, false, true);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (40, 'Stroll kraschar', true, false, false, true);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (41, 'En förare får 5 sekunders tillägg', true, false, false, true);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (42, 'Två bilar eller fler tar ut varandra i en sekvens', true, false, false, true);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (43, 'Sainz är inte överens med stallet om strategi', true, false, false, true);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (44, 'Gulflagg på första varvet', true, false, false, true);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (45, 'Ett team gör 3 depåstopp', true, false, false, true);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (46, 'Polesitter vinner inte', true, false, false, true);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (47, 'Någon utanför topp 3 på pallen (RB, F, McL, MB)', true, false, false, true);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (48, 'Stroll tar poäng', true, false, false, true);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (49, 'Albon tar poäng', true, false, false, true);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (50, 'Två virtuella säkerhetsbilar under racet', true, false, false, true);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (51, 'En förare får stallorder', true, false, false, true);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (52, 'En förare säger ”pip” under racet', true, false, false, true);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (53, 'Alonso vinner', true, false, false, true);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (54, 'Ocon kommer på pallen', true, false, false, true);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (55, 'Piastri tar poäng', true, false, false, true);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (56, 'Hamilton tar fler poäng än Perez', true, false, false, true);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (57, 'Haas tar poäng', true, false, false, true);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (58, 'Russel kommer på pallen', true, false, false, true);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (59, 'Verstappen bryter', true, false, false, true);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (60, 'Leclerc vinner', true, false, false, true);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (61, 'Bottas tar poäng', true, false, false, true);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (62, 'Williams tar poäng', true, false, false, true);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (63, 'Säkerhetsbil under racet', true, false, false, true);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (64, 'Perez vägrar lyda stallorder', true, false, false, true);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (65, 'Sainz vinner', true, false, false, true);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (66, 'Någon gissar på rätt depåtid', true, false, false, true);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (67, 'Minst 4 förare bryter', true, false, false, true);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (68, 'En förare slutar +/- 7 platser från kval', true, false, false, true);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (69, 'En McLaren slutar topp 10', true, false, false, true);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (70, 'En förare klagar på greppnivån', true, false, false, true);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (71, 'Ferrari tar ett kontraproduktivt beslut', true, false, false, true);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (72, 'En bil måste byta nos', true, false, false, true);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (73, 'Det regnar under racet (intermediates på)', true, false, false, true);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (74, 'En förare får straff efter kval och innan race', true, false, false, true);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (75, 'Perez får poäng för snabbaste varv', true, false, false, true);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (76, 'Hamilton blir Driver of the Day', true, false, false, true);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (77, 'Racet blir rödflaggat', true, false, false, true);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (78, 'Virtuell säkerhetsbil åtminstone 1 gång under racet', true, false, false, true);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (79, 'Ingen bil bryter', true, false, false, true);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (80, 'En bil starter från depån', true, false, false, true);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (81, 'En förare får en varning pga track limits', true, false, false, true);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (82, 'Alla på pallen har varit eller är världsmästare', true, false, false, true);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (83, 'Hamilton klagar på strategin', true, false, false, true);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (84, 'En förare klagar på annan förare', true, false, false, true);
INSERT INTO public.statement (id, text, race, qualifying, sprint_shootout, sprint_race) VALUES (85, 'Det blir race mellan teamkollegor (räcker med kort sådant)', true, false, false, true);
