begin;
alter table bingo_card_statement
    drop constraint bingo_card_statement_statement_fkey;

alter table public.verified_statement
    drop constraint verified_statement_statement_fkey;

delete
from statement;
INSERT INTO statement (id, text, race, qualifying, sprint_shootout, sprint_race, category, enabled)
VALUES (1, 'POLE: Ferrari', false, true, true, false, 'POLE_POSITION', true),
       (2, 'Q1: En Alpine åker ut', false, true, true, false, 'ALP_OUT', true),
       (3, '”Tow” till stallkompisen', false, true, true, false, 'NONE', true),
       (4, 'En förare säger ”pip”', true, true, true, true, 'NONE', true),
       (5, 'Kvalet blir rödflaggat', false, true, true, false, 'NONE', true),
       (6, 'Q3: En Haas eller Williams går till Q3', false, true, true, false, 'NONE', true),
       (7, 'Q2: En Red Bull åker ut', false, true, true, false, 'REB_OUT', true),
       (8, 'Q1: En Red Bull åker ut', false, true, true, false, 'REB_OUT', true),
       (9, 'Q3: En Sauber går till Q3', false, true, true, false, 'NONE', true),
       (10, 'Q2: En Racing Bull åker ut', false, true, true, false, 'RAB_OUT', true),
       (11, 'POLE: Mercedes', false, true, true, false, 'POLE_POSITION', true),
       (12, 'POLE: RedBull', false, true, true, false, 'POLE_POSITION', true),
       (13, 'POÄNG: Gul förare fler än svart', true, false, false, true, 'NONE', true),
       (14, 'POLE: Något annat stall än topp 4', false, true, true, false, 'POLE_POSITION', true),
       (15, 'En förare missar chans till snabb tid pga trafik', false, true, true, false, 'NONE', true),
       (16, 'Q3: En Aston Martin går till Q3', false, true, true, false, 'NONE', true),
       (17, 'MER: Antonelli kvalar ut Russel', false, true, true, false, 'NONE', true),
       (18, 'Gulflagg: Under kvalet', false, true, true, false, 'NONE', true),
       (19, 'En bil tappar en del', true, true, true, true, 'NONE', true),
       (20, 'Gulflagg: Under racet', true, false, false, true, 'NONE', true),
       (21, 'Q1: En Sauber åker ut', false, true, true, false, 'SAB_OUT', true),
       (22, 'En förare får straff/ reprimand innan kval', false, true, true, false, 'NONE', true),
       (23, 'Q3: En nykomling går till Q3', false, true, true, false, 'NONE', true),
       (24, 'Q1: En Aston Martin åker ut', false, true, true, false, 'AM_OUT', true),
       (25, 'Q2: En Aston Martin åker ut', false, true, true, false, 'AM_OUT', true),
       (26, 'Q1: En Ferrari åker ut', false, true, true, false, 'FER_OUT', true),
       (27, 'Q2: En Ferrari åker ut', false, true, true, false, 'FER_OUT', true),
       (28, 'Q1: En Mercedes åker ut', false, true, true, false, 'MER_OUT', true),
       (29, 'Q2: En Mercedes åker ut', false, true, true, false, 'MER_OUT', true),
       (30, 'En förare får sin tid struken pga track limits', false, true, true, false, 'NONE', true),
       (31, 'En förare får "notering för impeding"', false, true, true, false, 'NONE', true),
       (32, 'Q3: En Alpine slutar topp 5', false, true, true, false, 'NONE', true),
       (33, 'Kvalstarten blir uppskjuten', false, true, true, false, 'NONE', true),
       (34, 'En bil bryter under kvalet', false, true, true, false, 'BRYT', true),
       (35, 'En förare klagar på däcken', true, true, true, true, 'NONE', true),
       (36, 'Red Bull på pallen', true, false, false, true, 'PODIUM', true),
       (37, 'En bil börjar brinna', true, false, false, true, 'BRYT', true),
       (38, 'Två bilar har kontakt med varandra', true, false, false, true, 'NONE', true),
       (39, 'Red Bull vinner', true, false, false, true, 'RACE_WINNER', true),
       (40, 'Polesitter förlorar placering på varv 1', true, false, false, true, 'NONE', true),
       (41, 'En förare får tidstillägg', true, false, false, true, 'NONE', true),
       (42, 'Två bilar eller fler tar ut varandra', true, false, false, true, 'NONE', true),
       (43, 'En förare kritiserar strategin', true, false, false, false, 'NONE', true),
       (44, 'Gulflagg: På första varvet', true, false, false, true, 'NONE', true),
       (45, 'Ett team gör 3 depåstopp', true, false, false, false, 'NONE', true),
       (46, 'Polesitter vinner inte', true, false, false, true, 'NONE', true),
       (47, 'Någon utanför topp 4 på pallen', true, false, false, true, 'PODIUM', true),
       (48, 'POÄNG: Aston Martin', true, false, false, true, 'NONE', true),
       (49, 'POÄNG: Williams', true, false, false, true, 'NONE', true),
       (50, 'Varvade bilar får passera SC', true, false, false, true, 'NONE', true),
       (51, 'En förare får stallorder', true, false, false, true, 'NONE', true),
       (52, 'Annat team än toppteam vinner', true, false, false, true, 'RACE_WINNER', true),
       (53, 'McLaren vinner', true, false, false, true, 'RACE_WINNER', true),
       (54, 'Mercedes på pallen', true, false, false, true, 'PODIUM', true),
       (55, 'POÄNG: Haas', true, false, false, true, 'NONE', true),
       (56, 'POÄNG: Svart förare fler än gul', true, false, false, true, 'NONE', true),
       (57, 'POÄNG: Racing Bull', true, false, false, true, 'NONE', true),
       (58, 'Ferrari på pallen', true, false, false, true, 'PODIUM', true),
       (59, 'En av nykomlingarna bryter', true, false, false, true, 'BRYT', true),
       (60, 'Ferrari vinner', true, false, false, true, 'RACE_WINNER', true),
       (61, 'POÄNG: Alpine', true, false, false, true, 'NONE', true),
       (62, 'POÄNG: Sauber', true, false, false, true, 'NONE', true),
       (63, 'SC under racet', true, false, false, true, 'NONE', true),
       (64, 'En förare vägrar lyda stallorder', true, false, false, true, 'NONE', true),
       (65, 'Mercedes vinner', true, false, false, true, 'RACE_WINNER', true),
       (66, 'Någon gissar på rätt depåtid', true, false, false, false, 'NONE', true),
       (67, 'Minst 4 förare bryter', true, false, false, true, 'BRYT', true),
       (68, 'En förare slutar +/- 7 platser från kval', true, false, false, true, 'NONE', true),
       (69, 'Sist på gridden tar minst 1 plac på varv 1', true, false, false, true, 'NONE', true),
       (70, 'En förare klagar på greppnivån', true, true, true, true, 'NONE', true),
       (71, 'Ferrari tar ett icke produktivt beslut', true, false, false, true, 'NONE', true),
       (72, 'En bil måste byta nos', true, false, false, true, 'NONE', true),
       (73, 'Det regnar (intermediates på)', true, true, true, true, 'NONE', true),
       (74, 'Någon får straff efter kval och innan race', true, false, false, true, 'NONE', true),
       (75, 'Snabbaste varv: Norris', true, false, false, false, 'FASTEST_LAP', true),
       (76, 'Driver of the Day: Hamilton', true, false, false, false, 'DRIVER_OF_THE_DAY', true),
       (77, 'Racet blir rödflaggat', true, false, false, true, 'NONE', true),
       (78, 'VSC under racet', true, false, false, true, 'NONE', true),
       (79, 'Ingen bil bryter', true, false, false, true, 'BRYT', true),
       (80, 'En bil startar från depån', true, false, false, true, 'NONE', true),
       (81, 'En förare får en varning pga track limits', true, false, false, true, 'NONE', true),
       (82, 'Någon på pallen har inte varit världsmästare', true, false, false, true, 'PODIUM', true),
       (83, 'En förare klagar på strategin', true, true, true, true, 'NONE', true),
       (84, 'En förare klagar på annan förare', true, true, true, true, 'NONE', true),
       (85, 'Det blir race mellan teamkollegor', true, false, false, true, 'NONE', true),
       (86, 'POLE: McLaren', false, true, true, false, 'POLE_POSITION', true),
       (87, 'Q1: En McLaren åker ut', false, true, true, false, 'MCL_OUT', true),
       (88, 'Q2: En McLaren åker ut', false, true, true, false, 'MCL_OUT', true),
       (89, 'Q3: En Racing Bull går till Q3', false, true, true, false, 'NONE', true),
       (90, 'Q1: En Racing Bull åker ut', false, true, true, false, 'RAB_OUT', true),
       (91, 'Q2: En Sauber åker ut', false, true, true, false, 'SAB_OUT', true),
       (92, 'En bil touchar eller kraschar i en barriär', true, true, true, true, 'NONE', true),
       (93, 'Driver of the Day: Verstappen', true, false, false, false, 'DRIVER_OF_THE_DAY', true),
       (94, 'Driver of the Day: Hülkenberg', true, false, false, false, 'DRIVER_OF_THE_DAY', true),
       (95, 'Driver of the Day: Lawson', true, false, false, false, 'DRIVER_OF_THE_DAY', true),
       (96, 'Driver of the Day: Norris', true, false, false, false, 'DRIVER_OF_THE_DAY', true),
       (97, 'Driver of the Day: Piastri', true, false, false, false, 'DRIVER_OF_THE_DAY', true),
       (98, 'Driver of the Day: Sainz', true, false, false, false, 'DRIVER_OF_THE_DAY', true),
       (99, 'Driver of the Day: Leclerc', true, false, false, false, 'DRIVER_OF_THE_DAY', true),
       (100, 'Driver of the Day: Russel', true, false, false, false, 'DRIVER_OF_THE_DAY', true),
       (101, 'Driver of the Day: Alonso', true, false, false, false, 'DRIVER_OF_THE_DAY', true),
       (102, 'Driver of the Day: Albon', true, false, false, false, 'DRIVER_OF_THE_DAY', true),
       (103, 'Driver of the Day: Gasly', true, false, false, false, 'DRIVER_OF_THE_DAY', true),
       (104, 'Driver of the Day: Ocon', true, false, false, false, 'DRIVER_OF_THE_DAY', true),
       (105, 'Driver of the Day: Stroll', true, false, false, false, 'DRIVER_OF_THE_DAY', true),
       (106, 'Däcken börjar blistra för en förare', true, false, false, false, 'NONE', true),
       (107, 'En förare är frustrerad över sitt agerande', true, true, true, true, 'NONE', true),
       (108, 'Förare ber depån kolla bilen', true, false, false, false, 'NONE', true),
       (109, 'Snabbaste varv: Verstappen', true, false, false, false, 'FASTEST_LAP', true),
       (110, 'Snabbaste varv: Leclerc', true, false, false, false, 'FASTEST_LAP', true),
       (111, 'Snabbaste varv: Piastri', true, false, false, false, 'FASTEST_LAP', true),
       (112, 'Snabbaste varv: Hamilton', true, false, false, false, 'FASTEST_LAP', true),
       (113, 'Snabbaste varv: Russel', true, false, false, false, 'FASTEST_LAP', true),
       (114, 'En förare får sladd på bilen', true, true, true, true, 'NONE', true),
       (115, 'Långsamt depåstopp >4 sek', true, false, false, false, 'NONE', true),
       (116, 'En förare klagar på bilen', true, true, true, true, 'NONE', true),
       (117, 'Depån uppmanar till omkörning', true, false, false, true, 'NONE', true),
       (118, 'McLaren på pallen', true, false, false, true, 'PODIUM', true),
       (119, 'Ett stall gör en "double stack"', true, false, false, false, 'NONE', true),
       (120, 'En förare använder avåkningszon', true, true, true, true, 'NONE', true),
       (121, 'Båda bilarna i ett stall bryter', true, false, false, true, 'BRYT', true),
       (122, 'Ett stall noteras för "Unsafe release"', true, true, false, false, 'NONE', true),
       (123, 'En förare hyllar fansen', true, true, true, true, 'NONE', true),
       (124, 'Q1: En Williams åker ut', false, true, true, false, 'WIL_OUT', true),
       (125, 'Snabbaste varv: Antonelli', true, false, false, false, 'FASTEST_LAP', true),
       (126, 'Q1: 10 förare kvalar inom en sekund', false, true, true, false, 'NONE', true),
       (127, 'Q2: 10 förare kvalar inom en sekund', false, true, true, false, 'NONE', true),
       (128, 'Q3: 5 förare inom en sekund efter kval', false, true, true, false, 'NONE', true),
       (129, 'Ett däck sitter inte på efter stopp', true, false, false, false, 'NONE', true),
       (131, 'RaceDirector har noterat en händelse', true, true, true, true, 'NONE', true),
       (132, 'Teamet diskuterar strategin med föraren', true, false, false, false, 'NONE', true),
       (165, 'En förare tjuvstartar', true, false, false, true, 'NONE', true),
       (198, 'Minst 16 startar på samma gummiblandning', true, false, false, true, 'NONE', true),
       (199, 'WIL: Sainz kvalar ut Albon', false, true, true, false, 'NONE', true),
       (200, 'FER: Hamilton kvalar ut Leclerc', false, true, true, false, 'NONE', true),
       (201, 'RAB: Hadjar kvalar ut Lawson', false, true, true, false, 'NONE', true),
       (202, 'Ett stall kvalar 1:a och 2:a', false, true, true, false, 'NONE', true),
       (203, 'McL: Piastri kvalar ut Norris', false, true, true, false, 'NONE', true),
       (204, 'AM: Stroll kvalar ut Alonso', false, true, true, false, 'NONE', true),
       (205, 'REB: Tsunoda kvalar ut Verstappen', false, true, true, false, 'NONE', true),
       (206, 'HaaS: Bearman kvalar ut Ocon', false, true, true, false, 'NONE', true),
       (207, 'SAU: Colapinto kvalar ut Hülkenberg', false, true, true, false, 'NONE', true),
       (208, 'ALP: Doohan kvalar ut Gasly', false, true, true, false, 'NONE', true),
       (209, 'Driver of the Day: Antonelli', true, false, false, false, 'DRIVER_OF_THE_DAY', true),
       (210, 'Driver of the Day: Tsunoda', true, false, false, false, 'DRIVER_OF_THE_DAY', true),
       (211, 'Driver of the Day: Bearman', true, false, false, false, 'DRIVER_OF_THE_DAY', true),
       (212, 'Driver of the Day: Hadjar', true, false, false, false, 'DRIVER_OF_THE_DAY', true),
       (213, 'Q2: En Alpine åker ut', false, true, true, false, 'ALP_OUT', true),
       (214, 'Q2: En Haas åker ut', false, true, true, false, 'HAA_OUT', true),
       (215, 'Q2: En Williams åker ut', false, true, true, false, 'WIL_OUT', true),
       (216, 'POÄNG: Red Bull fler än Ferrari', true, false, false, true, 'NONE', true),
       (217, '3 eller fler förare leder under racets gång', true, false, false, true, 'NONE', true)
;

SELECT setval(
               'statement_id_seq',
               (SELECT MAX(id) FROM statement) + 1
       );

alter table bingo_card_statement
    add constraint bingo_card_statement_statement_fkey
        foreign key (statement) references statement;

alter table verified_statement
    add constraint verified_statement_statement_fkey
        foreign key (statement) references statement;

commit;
