insert into contract (driver, team)
values ('alb', 'williams'),
       ('alo', 'astonMartin'),
       ('ant', 'mercedes'),
       ('bea', 'haas'),
       ('bor', 'audi'),
       ('bot', 'cadillac'),
       ('col', 'alpine'),
       ('gas', 'alpine'),
       ('had', 'redBull'),
       ('ham', 'ferrari'),
       ('hul', 'audi'),
       ('law', 'racingBulls'),
       ('lec', 'ferrari'),
       ('lin', 'racingBulls'),
       ('nor', 'mclaren'),
       ('oco', 'haas'),
       ('per', 'cadillac'),
       ('pia', 'mclaren'),
       ('rus', 'mercedes'),
       ('sai', 'williams'),
       ('str', 'astonMartin'),
       ('ver', 'redBull');
